# Generated by Django 4.1.2 on 2022-11-03 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Categoryid", models.CharField(max_length=10)),
                ("Categoryname", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prodid", models.CharField(max_length=7, unique=True)),
                ("Prodname", models.CharField(max_length=50)),
                ("Prodtype", models.CharField(max_length=30)),
                ("Price", models.FloatField()),
                (
                    "Categoryid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ProdManagement.category",
                    ),
                ),
            ],
        ),
    ]
