
pyms:
  services:
    requests:
      propogate_headers: true
    tracer:
      client: 'jaeger'
      host: 'localhost'
      component_name: "Python Microservice"
  config:
    APP_NAME: "Python Microservice"
    debug: true

