# Generated by Django 4.1.2 on 2022-10-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prodname", models.CharField(max_length=100)),
                ("mnftr", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("prodtype", models.CharField(max_length=100)),
                ("price", models.FloatField()),
            ],
        ),
    ]
